### ISSUE TITLE
import 'package:abherbs_flutter/keys.dart'

### ISSUE THREAD

**Issue by Chamais** [benadrasni/abherbs_flutter#7]
Hello, I am learning in flutter and tried to test this application, but when compiling it is not possible to solve the referenced import, because the keys.dart module does not exist

**Comment by benadrasni** [comment]
Hi,

you have to create your own keys.

Regards

Adrian

**Comment by Chamais** [comment]
Hi Adrian
I understand what you tell me, but not knowing the operation and the objective of the Keys.dart module in your package, then, I do not know how I can create my own keys.

Anyway, I take this opportunity to congratulate you for the good and great work you have done and we can share it for this great community through GitHub.

Thanks a lot.

Best regards

**Comment by benadrasni** [comment]
Thanks.

Anyway in order to make this application working you also have to have
firebase database with certain structure, admob account, some Google APIs
enabled...

**Comment by Chamais** [comment]
Hi again,
I understand the difficulty of the project and maybe I should limit my horizon since I am still in the learning process.
Actually, what I was looking for was a model to make a personal application that will help me in the identification and storage of mycological species, since I am a great fan of the fungi kingdom.
I have a large file of photos that I have been doing in the last few years and now I want to give it a database or Json where I can check the characteristics, class, ordem family, gender, etc.
I already know that there are similar applications in the market and very cheap, but I prefer to do them by myself and expand the database with the new species that can be found.
Thank you.

**Comment by Chamais** [comment]
Hello again
I just wanted to inform you that after the last update (april-8-2019), the following errors occur:

Flutter analyze

Analyzing abherbs_flutter-master...

  error - Undefined name 'firebaseSettingsGenericEntities' - lib\search\search_photo.dart:162:45 - undefined_identifier

  error - Undefined name 'firebaseAttributeFreebase' - lib\search\search_taxonomy.dart:141:100 - undefined_identifier

2 issues found. (ran in 2.5s)

Best Regards

**Comment by benadrasni** [comment]
These identifiers are defined in utils/utils.dart.

**Comment by Chamais** [comment]
Hi,
In utils.dart only this identifier is defined: const String firebaseSettingsGenericLabels = "settings / generic_labels";

**Comment by Chamais** [comment]
Now everything is ok, but the pubspec.yaml path in the dependencies does not support it

**Comment by benadrasni** [comment]
I had to fix some libraries so I have them locally (e.g.
firebase_ml_vision, image_picker)

**Comment by Chamais** [comment]
Totally agree, you're absolutely right
This App is improving every day more and it helps us a lot in the identification of plants.
Thanks a lot

**Comment by esirioneyibo** [comment]
hello,
I just wanted to add mine as well. On the keys issue, we are not asking you to reveal your keys. It will be nice and easy for whoever is trying your code to be able to either run and modify it as they can or will. 
Any example you provide as a guide will help whoever is following or looking at your code. 
Because right now, without any reference on how to make the key file, it is impossible to compile your code.

**Comment by benadrasni** [comment]
Hello,

it is not only keys, also database structure is not revealed and without
proper database project won't work.

Regards
