### ISSUE TITLE
Help for App tests

### ISSUE THREAD

**Issue by Chamais** [benadrasni/abherbs_flutter#9]
Hello,
After several attempts to try this App with the Emulator, I want to make several comments:
• In the first place, we must thank the author for having made available to the GitHub Community such an advanced and refined way of creating Dart code.
• Secondly, ask him to include a copy of the keys.dart module with simulated content, so we can easily include our own keys.
• Equally, it would be convenient to illustrate us in the organization of the firebase database so that we can also create it with our own data.
All this, we would greatly facilitate to perform the appropriate tests in the Emulator of Android Studio or IntelliJ IDEA for later, to be able to make our contribution to possible improvements or detection of errors.
Thank you so much for everything.

**Comment by engmms** [comment]
really it is great App but has a lot of issues ,,example 
Error on line 46, column 5 of pubspec.yaml: A dependency may only have one source.

   ╷

46 │ ┌     path: ../flutter_screen

47 │ │     flutter_country_picker:


48 │ │       path: ../flutter_country_picker
49 │ │     firebase_ml_vision:


50 │ │       path: ../plugins/packages/firebase_ml_vision
51 │ │ 

52 │ │   # The following adds the Cupertino Icons font to your application.

53 │ │   # Use with the CupertinoIcons class for iOS style icons.

54 │ │   cupertino_icons: ^0.1.2

   │ └──^

   ╵
pub get failed (65)

my pubspec.yaml

screen:
    path: ../flutter_screen
    flutter_country_picker:
      path: ../flutter_country_picker
    firebase_ml_vision:
      path: ../plugins/packages/firebase_ml_vision

**Comment by benadrasni** [comment]
I have some libraries installed locally hence "path" attribute for "flutter_country_picker", "firebase_ml_vision" and "flutter_screen". These libraries have separate repositories.

**Comment by sarabepu** [comment]
Hi, I'm trying to test this app and have the same problem. How did you test it? I'm very interested in understanding this app for my construction of mobile applications course. Thank you!
